
version: 3
jobs:
  build:
    working_directory: ~/seg2x05-project-team-f19-1
    docker:
      - image: ccistaging/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      